"""add_notification_table

Revision ID: a0ada9774936
Revises: d0e58437af70
Create Date: 2026-04-24 14:30:15.910949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ada9774936'
down_revision: Union[str, Sequence[str], None] = 'd0e58437af70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='通知类型：version_update / system'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='优先级：info / warning / error'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('extra_data', sa.Text(), nullable=True, comment='JSON扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
