/* AUTO-GENERATED by scripts/generate-advanced-search-contract.js. DO NOT EDIT. */

export type AdvancedSearchFieldKind =
  | 'text'
  | 'number'
  | 'date'
  | 'select'
  | 'multiSelect'
  | 'boolean'

export interface AdvancedSearchOperatorConfig {
  value: string
  /** 中文展示名（契约源，运行时按 locale 二选一展示） */
  label: string
  /** 英文展示名（契约源，桌面双语 P3-1 起与 label 成对出现） */
  labelEn: string
  /** 后端稳定操作符标识 */
  backendValue: string
}

export interface AdvancedSearchFieldContract {
  kind: AdvancedSearchFieldKind
  operators: readonly string[]
}

export const ADVANCED_SEARCH_CONTRACT_VERSION = 3
export const ADVANCED_SEARCH_MAX_REGEX_CONDITIONS = 3
export const ADVANCED_SEARCH_MAX_REGEX_PATTERN_LENGTH = 256

export const ADVANCED_SEARCH_FIELDS: Readonly<Record<string, AdvancedSearchFieldContract>> = Object.freeze(
{
  "info_id": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "starts_with",
      "ends_with",
      "not_starts_with",
      "not_ends_with",
      "in",
      "not_in",
      "regex"
    ]
  },
  "downloader_id": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "in",
      "not_in"
    ]
  },
  "downloader_name": {
    "kind": "multiSelect",
    "operators": [
      "eq",
      "ne",
      "in",
      "not_in"
    ]
  },
  "torrent_id": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "starts_with",
      "ends_with",
      "not_starts_with",
      "not_ends_with",
      "in",
      "not_in",
      "regex"
    ]
  },
  "hash": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "starts_with",
      "ends_with",
      "not_starts_with",
      "not_ends_with",
      "in",
      "not_in",
      "regex"
    ]
  },
  "name": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "starts_with",
      "ends_with",
      "not_starts_with",
      "not_ends_with",
      "in",
      "not_in",
      "regex"
    ]
  },
  "save_path": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "starts_with",
      "ends_with",
      "not_starts_with",
      "not_ends_with",
      "in",
      "not_in",
      "regex"
    ]
  },
  "size": {
    "kind": "number",
    "operators": [
      "eq",
      "ne",
      "gt",
      "gte",
      "lt",
      "lte",
      "between"
    ]
  },
  "status": {
    "kind": "multiSelect",
    "operators": [
      "eq",
      "ne",
      "in",
      "not_in"
    ]
  },
  "added_date": {
    "kind": "date",
    "operators": [
      "eq",
      "ne",
      "gt",
      "gte",
      "lt",
      "lte",
      "between",
      "last_days",
      "date_range"
    ]
  },
  "added_time": {
    "kind": "date",
    "operators": [
      "eq",
      "ne",
      "gt",
      "gte",
      "lt",
      "lte",
      "between",
      "last_days",
      "date_range"
    ]
  },
  "completed_date": {
    "kind": "date",
    "operators": [
      "eq",
      "ne",
      "gt",
      "gte",
      "lt",
      "lte",
      "between",
      "last_days",
      "date_range",
      "is_null",
      "is_not_null"
    ]
  },
  "ratio": {
    "kind": "number",
    "operators": [
      "eq",
      "ne",
      "gt",
      "gte",
      "lt",
      "lte",
      "between",
      "is_null",
      "is_not_null"
    ]
  },
  "ratio_limit": {
    "kind": "number",
    "operators": [
      "eq",
      "ne",
      "gt",
      "gte",
      "lt",
      "lte",
      "between",
      "is_null",
      "is_not_null"
    ]
  },
  "tags": {
    "kind": "multiSelect",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "contains_any",
      "contains_all",
      "not_contains_any",
      "not_contains_all",
      "is_null",
      "is_not_null"
    ]
  },
  "category": {
    "kind": "multiSelect",
    "operators": [
      "eq",
      "ne",
      "in",
      "not_in",
      "is_null",
      "is_not_null"
    ]
  },
  "super_seeding": {
    "kind": "select",
    "operators": [
      "eq",
      "ne"
    ]
  },
  "enabled": {
    "kind": "boolean",
    "operators": [
      "eq",
      "ne"
    ]
  },
  "tracker_url": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "starts_with",
      "ends_with",
      "not_starts_with",
      "not_ends_with",
      "in",
      "not_in",
      "regex"
    ]
  },
  "tracker_msg": {
    "kind": "text",
    "operators": [
      "eq",
      "ne",
      "contains",
      "not_contains",
      "starts_with",
      "ends_with",
      "not_starts_with",
      "not_ends_with",
      "in",
      "not_in",
      "regex"
    ]
  }
}
)

export const ADVANCED_SEARCH_OPERATOR_GROUPS: Readonly<
  Record<AdvancedSearchFieldKind, readonly AdvancedSearchOperatorConfig[]>
> = Object.freeze(
{
  "text": [
    {
      "value": "contains",
      "label": "包含",
      "labelEn": "Contains",
      "backendValue": "contains"
    },
    {
      "value": "not_contains",
      "label": "不包含",
      "labelEn": "Does not contain",
      "backendValue": "not_contains"
    },
    {
      "value": "equals",
      "label": "等于",
      "labelEn": "Equals",
      "backendValue": "eq"
    },
    {
      "value": "not_equals",
      "label": "不等于",
      "labelEn": "Does not equal",
      "backendValue": "ne"
    },
    {
      "value": "starts_with",
      "label": "开头是",
      "labelEn": "Starts with",
      "backendValue": "starts_with"
    },
    {
      "value": "ends_with",
      "label": "结尾是",
      "labelEn": "Ends with",
      "backendValue": "ends_with"
    },
    {
      "value": "regex",
      "label": "正则匹配",
      "labelEn": "Regex match",
      "backendValue": "regex"
    }
  ],
  "number": [
    {
      "value": "equals",
      "label": "等于",
      "labelEn": "Equals",
      "backendValue": "eq"
    },
    {
      "value": "not_equals",
      "label": "不等于",
      "labelEn": "Does not equal",
      "backendValue": "ne"
    },
    {
      "value": "greater_than",
      "label": "大于",
      "labelEn": "Greater than",
      "backendValue": "gt"
    },
    {
      "value": "less_than",
      "label": "小于",
      "labelEn": "Less than",
      "backendValue": "lt"
    },
    {
      "value": "greater_equal",
      "label": "大于等于",
      "labelEn": "Greater than or equal",
      "backendValue": "gte"
    },
    {
      "value": "less_equal",
      "label": "小于等于",
      "labelEn": "Less than or equal",
      "backendValue": "lte"
    },
    {
      "value": "between",
      "label": "介于",
      "labelEn": "Between",
      "backendValue": "between"
    },
    {
      "value": "is_null",
      "label": "未设置",
      "labelEn": "Not set",
      "backendValue": "is_null"
    },
    {
      "value": "is_not_null",
      "label": "已设置",
      "labelEn": "Is set",
      "backendValue": "is_not_null"
    }
  ],
  "date": [
    {
      "value": "equals",
      "label": "等于",
      "labelEn": "Equals",
      "backendValue": "eq"
    },
    {
      "value": "not_equals",
      "label": "不等于",
      "labelEn": "Does not equal",
      "backendValue": "ne"
    },
    {
      "value": "greater_than",
      "label": "晚于",
      "labelEn": "After",
      "backendValue": "gt"
    },
    {
      "value": "less_than",
      "label": "早于",
      "labelEn": "Before",
      "backendValue": "lt"
    },
    {
      "value": "greater_equal",
      "label": "不早于",
      "labelEn": "On or after",
      "backendValue": "gte"
    },
    {
      "value": "less_equal",
      "label": "不晚于",
      "labelEn": "On or before",
      "backendValue": "lte"
    },
    {
      "value": "last_days",
      "label": "最近N天",
      "labelEn": "Last N days",
      "backendValue": "last_days"
    },
    {
      "value": "date_range",
      "label": "日期范围",
      "labelEn": "Date range",
      "backendValue": "date_range"
    },
    {
      "value": "is_null",
      "label": "未设置",
      "labelEn": "Not set",
      "backendValue": "is_null"
    },
    {
      "value": "is_not_null",
      "label": "已设置",
      "labelEn": "Is set",
      "backendValue": "is_not_null"
    }
  ],
  "select": [
    {
      "value": "equals",
      "label": "等于",
      "labelEn": "Equals",
      "backendValue": "eq"
    },
    {
      "value": "not_equals",
      "label": "不等于",
      "labelEn": "Does not equal",
      "backendValue": "ne"
    },
    {
      "value": "in",
      "label": "在列表中",
      "labelEn": "In list",
      "backendValue": "in"
    },
    {
      "value": "not_in",
      "label": "不在列表中",
      "labelEn": "Not in list",
      "backendValue": "not_in"
    }
  ],
  "multiSelect": [
    {
      "value": "in",
      "label": "包含任意",
      "labelEn": "Match any",
      "backendValue": "in"
    },
    {
      "value": "not_in",
      "label": "不包含任意",
      "labelEn": "Match none",
      "backendValue": "not_in"
    },
    {
      "value": "contains_any",
      "label": "包含任意",
      "labelEn": "Contains any",
      "backendValue": "contains_any"
    },
    {
      "value": "not_contains_any",
      "label": "不包含任意",
      "labelEn": "Contains none",
      "backendValue": "not_contains_any"
    },
    {
      "value": "is_null",
      "label": "未设置",
      "labelEn": "Not set",
      "backendValue": "is_null"
    },
    {
      "value": "is_not_null",
      "label": "已设置",
      "labelEn": "Is set",
      "backendValue": "is_not_null"
    }
  ],
  "boolean": [
    {
      "value": "equals",
      "label": "等于",
      "labelEn": "Equals",
      "backendValue": "eq"
    },
    {
      "value": "not_equals",
      "label": "不等于",
      "labelEn": "Does not equal",
      "backendValue": "ne"
    }
  ]
}
)

export const ADVANCED_SEARCH_OPERATOR_MAPPING: Readonly<Record<string, string>> = Object.freeze(
{
  "contains": "contains",
  "not_contains": "not_contains",
  "equals": "eq",
  "not_equals": "ne",
  "starts_with": "starts_with",
  "ends_with": "ends_with",
  "regex": "regex",
  "greater_than": "gt",
  "less_than": "lt",
  "greater_equal": "gte",
  "less_equal": "lte",
  "between": "between",
  "is_null": "is_null",
  "is_not_null": "is_not_null",
  "last_days": "last_days",
  "date_range": "date_range",
  "in": "in",
  "not_in": "not_in",
  "contains_any": "contains_any",
  "not_contains_any": "not_contains_any"
}
)

export const ADVANCED_SEARCH_REVERSE_OPERATOR_MAPPING: Readonly<Record<string, string>> = Object.freeze(
{
  "contains": "contains",
  "not_contains": "not_contains",
  "eq": "equals",
  "ne": "not_equals",
  "starts_with": "starts_with",
  "ends_with": "ends_with",
  "regex": "regex",
  "gt": "greater_than",
  "lt": "less_than",
  "gte": "greater_equal",
  "lte": "less_equal",
  "between": "between",
  "is_null": "is_null",
  "is_not_null": "is_not_null",
  "last_days": "last_days",
  "date_range": "date_range",
  "in": "in",
  "not_in": "not_in",
  "contains_any": "contains_any",
  "not_contains_any": "not_contains_any"
}
)

export const ADVANCED_SEARCH_NEGATED_OPERATORS: Readonly<Record<string, string>> = Object.freeze(
{
  "eq": "ne",
  "ne": "eq",
  "contains": "not_contains",
  "not_contains": "contains",
  "starts_with": "not_starts_with",
  "not_starts_with": "starts_with",
  "ends_with": "not_ends_with",
  "not_ends_with": "ends_with",
  "in": "not_in",
  "not_in": "in",
  "contains_any": "not_contains_any",
  "not_contains_any": "contains_any",
  "contains_all": "not_contains_all",
  "not_contains_all": "contains_all",
  "gt": "lte",
  "gte": "lt",
  "lt": "gte",
  "lte": "gt"
}
)
