"""add tracker_reannounce_config table

Revision ID: d0e58437af70
Revises: e2a02abcf912
Create Date: 2026-04-10 12:02:30.610609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e58437af70'
down_revision: Union[str, Sequence[str], None] = 'e2a02abcf912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_reannounce_config',
    sa.Column('id_', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('domain_pattern', sa.String(length=256), nullable=False, comment='域名匹配模式（支持%通配符）'),
    sa.Column('domain_display_name', sa.String(length=100), nullable=False, comment='域名显示名称'),
    sa.Column('interval_minutes', sa.Integer(), nullable=False, comment='汇报间隔（分钟）'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_announce_time', sa.DATETIME(), nullable=True, comment='最后一次汇报时间'),
    sa.Column('create_time', sa.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=False, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=False, comment='更新人'),
    sa.Column('dr', sa.Integer(), nullable=False, comment='删除状态，0是未删除，1是逻辑删除'),
    sa.PrimaryKeyConstraint('id_'),
    comment='Tracker汇报站点配置表'
    )
    op.create_index('idx_reannounce_domain', 'tracker_reannounce_config', ['domain_pattern'], unique=False)
    op.create_index('idx_reannounce_enabled', 'tracker_reannounce_config', ['enabled'], unique=False)
    op.create_index(op.f('ix_tracker_reannounce_config_id_'), 'tracker_reannounce_config', ['id_'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_reannounce_config_id_'), table_name='tracker_reannounce_config')
    op.drop_index('idx_reannounce_enabled', table_name='tracker_reannounce_config')
    op.drop_index('idx_reannounce_domain', table_name='tracker_reannounce_config')
    op.drop_table('tracker_reannounce_config')
    # ### end Alembic commands ###
