"""fix_downloader_type_to_integer

Revision ID: e2a02abcf912
Revises: 
Create Date: 2026-03-07 18:59:32.611061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a02abcf912'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bt_downloaders',
    sa.Column('downloader_id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_search', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('downloader_type', sa.Integer(), nullable=False, comment='下载器类型：0=qBittorrent, 1=Transmission'),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('is_ssl', sa.Boolean(), nullable=True),
    sa.Column('dr', sa.Integer(), nullable=True),
    sa.Column('path_mapping', sa.Text(), nullable=True, comment='路径映射配置（JSON格式）'),
    sa.Column('path_mapping_rules', sa.Text(), nullable=True, comment='路径映射规则配置（多行文本，格式：源路径{#**#}目标路径）'),
    sa.Column('torrent_save_path', sa.String(length=500), nullable=True, comment='种子保存目录路径（应用运行环境可直接访问的绝对路径）'),
    sa.PrimaryKeyConstraint('downloader_id')
    )
    op.create_index(op.f('ix_bt_downloaders_downloader_id'), 'bt_downloaders', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_bt_downloaders_host'), 'bt_downloaders', ['host'], unique=False)
    op.create_index(op.f('ix_bt_downloaders_nickname'), 'bt_downloaders', ['nickname'], unique=False)
    op.create_index(op.f('ix_bt_downloaders_port'), 'bt_downloaders', ['port'], unique=False)
    op.create_index(op.f('ix_bt_downloaders_username'), 'bt_downloaders', ['username'], unique=False)
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('cron_task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('task_name', sa.String(length=200), nullable=False, comment='任务名称'),
    sa.Column('task_code', sa.String(length=50), nullable=False, comment='任务编码'),
    sa.Column('task_status', sa.Integer(), nullable=False, comment='任务状态，0等待运行，1运行中，2空闲'),
    sa.Column('task_type', sa.Integer(), nullable=False, comment='脚本类型，0-shell脚本，1-cmd脚本，2-powershell脚本，3-python脚本，4-python内部类，5-清理回收站任务'),
    sa.Column('executor', sa.Text(), nullable=False, comment='执行脚本内容或路径'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='启用状态'),
    sa.Column('last_execute_time', sa.DateTime(), nullable=True, comment='上次运行时间'),
    sa.Column('last_execute_duration', sa.Integer(), nullable=True, comment='上次运行持续时间，单位秒'),
    sa.Column('cron_plan', sa.String(length=100), nullable=False, comment='运行计划周期'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='任务描述'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='超时时间(秒)'),
    sa.Column('max_retry_count', sa.Integer(), nullable=True, comment='最大重试次数'),
    sa.Column('retry_interval', sa.Integer(), nullable=True, comment='重试间隔(秒)'),
    sa.Column('dr', sa.Integer(), nullable=False, comment='逻辑删除标识，1为逻辑删除，0为未删除'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=False, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=False, comment='更新人'),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('task_code')
    )
    op.create_table('downloader_capabilities',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('downloader_id', sa.String(), nullable=False, comment='下载器ID，关联bt_downloaders表'),
    sa.Column('downloader_setting_id', sa.Integer(), nullable=True, comment='下载器配置ID（可选），关联downloader_settings表'),
    sa.Column('supports_speed_scheduling', sa.Boolean(), server_default='0', nullable=False, comment='是否支持分时段限速（应用层实现）'),
    sa.Column('supports_transfer_speed', sa.Boolean(), server_default='1', nullable=False, comment='是否支持传输速度控制'),
    sa.Column('supports_connection_limits', sa.Boolean(), server_default='1', nullable=False, comment='是否支持连接限制'),
    sa.Column('supports_queue_settings', sa.Boolean(), server_default='1', nullable=False, comment='是否支持队列设置'),
    sa.Column('supports_download_paths', sa.Boolean(), server_default='0', nullable=False, comment='是否支持路径设置（Transmission支持）'),
    sa.Column('supports_port_settings', sa.Boolean(), server_default='1', nullable=False, comment='是否支持端口设置'),
    sa.Column('supports_advanced_settings', sa.Boolean(), server_default='1', nullable=False, comment='是否支持高级设置'),
    sa.Column('supports_peer_limits', sa.Boolean(), server_default='0', nullable=False, comment='是否支持Peer限制'),
    sa.Column('extended_capabilities', sa.Text(), nullable=True, comment='扩展能力配置（JSON格式），用于存储未来新增的能力开关'),
    sa.Column('synced_from_downloader', sa.Boolean(), server_default='0', nullable=False, comment='是否已从下载器同步过能力'),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True, comment='最后一次同步时间'),
    sa.Column('manual_override', sa.Boolean(), server_default='0', nullable=False, comment='是否为用户手动覆盖（手动覆盖后不再自动同步）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloader_capabilities_downloader_id'), 'downloader_capabilities', ['downloader_id'], unique=True)
    op.create_index(op.f('ix_downloader_capabilities_downloader_setting_id'), 'downloader_capabilities', ['downloader_setting_id'], unique=False)
    op.create_index(op.f('ix_downloader_capabilities_id'), 'downloader_capabilities', ['id'], unique=False)
    op.create_table('downloader_path_maintenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('downloader_id', sa.String(length=36), nullable=False, comment='下载器ID（UUID字符串）'),
    sa.Column('path_type', sa.String(length=20), nullable=False, comment='路径类型：default=默认路径，active=在用路径'),
    sa.Column('path_value', sa.String(length=500), nullable=False, comment='路径值（绝对路径）'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('torrent_count', sa.Integer(), nullable=False, comment='使用该路径的种子数量'),
    sa.Column('last_updated_time', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('downloader_id', 'path_type', 'path_value', name='uq_downloader_path_type_value')
    )
    op.create_index(op.f('ix_downloader_path_maintenance_downloader_id'), 'downloader_path_maintenance', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_downloader_path_maintenance_path_type'), 'downloader_path_maintenance', ['path_type'], unique=False)
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_logs_id'), 'login_logs', ['id'], unique=False)
    op.create_table('seed_transfer_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='操作类型：seed_transfer'),
    sa.Column('operation_time', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='操作用户名'),
    sa.Column('source_downloader_id', sa.Integer(), nullable=True, comment='源下载器ID'),
    sa.Column('source_downloader_name', sa.String(length=200), nullable=True, comment='源下载器昵称'),
    sa.Column('target_downloader_id', sa.Integer(), nullable=True, comment='目标下载器ID'),
    sa.Column('target_downloader_name', sa.String(length=200), nullable=True, comment='目标下载器昵称'),
    sa.Column('torrent_name', sa.String(length=500), nullable=True, comment='种子名称'),
    sa.Column('info_hash', sa.String(length=40), nullable=True, comment='种子的 info_hash'),
    sa.Column('source_path', sa.String(length=500), nullable=True, comment='源路径'),
    sa.Column('target_path', sa.String(length=500), nullable=True, comment='目标路径'),
    sa.Column('delete_source', sa.Boolean(), nullable=False, comment='是否删除原种子'),
    sa.Column('transfer_status', sa.String(length=20), nullable=False, comment='转移状态：success/failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（如果失败）'),
    sa.Column('transfer_duration', sa.BigInteger(), nullable=True, comment='转移耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_transfer_audit_log_info_hash'), 'seed_transfer_audit_log', ['info_hash'], unique=False)
    op.create_index(op.f('ix_seed_transfer_audit_log_operation_time'), 'seed_transfer_audit_log', ['operation_time'], unique=False)
    op.create_index(op.f('ix_seed_transfer_audit_log_transfer_status'), 'seed_transfer_audit_log', ['transfer_status'], unique=False)
    op.create_index(op.f('ix_seed_transfer_audit_log_user_id'), 'seed_transfer_audit_log', ['user_id'], unique=False)
    op.create_table('torrent_audit_log',
    sa.Column('log_id', sa.String(length=36), nullable=False, comment='日志主键'),
    sa.Column('torrent_info_id', sa.String(length=36), nullable=True, comment='关联种子主键'),
    sa.Column('operation_type', sa.String(length=50), nullable=True, comment='操作类型'),
    sa.Column('operation_detail', sa.Text(), nullable=True, comment='操作详情（JSON格式）'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='修改前的值（JSON）'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='修改后的值（JSON）'),
    sa.Column('operator', sa.String(length=50), nullable=True, comment='操作人'),
    sa.Column('operation_time', sa.DATETIME(), nullable=True, comment='操作时间'),
    sa.Column('operation_result', sa.String(length=20), nullable=True, comment='操作结果：success/failed/partial'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（如果失败）'),
    sa.Column('downloader_id', sa.String(length=36), nullable=True, comment='下载器ID'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='日志创建时间'),
    sa.Column('torrent_name', sa.String(length=255), nullable=True, comment='种子名称（冗余字段，用于列表显示和搜索）'),
    sa.Column('downloader_name', sa.String(length=100), nullable=True, comment='下载器名称（冗余字段，用于列表显示）'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='操作来源IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='浏览器/客户端信息'),
    sa.Column('request_id', sa.String(length=36), nullable=True, comment='请求唯一标识（用于追踪整个请求链路）'),
    sa.Column('session_id', sa.String(length=36), nullable=True, comment='会话ID（用于关联同一会话的多个操作）'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_torrent_audit_log_downloader_id'), 'torrent_audit_log', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_ip_address'), 'torrent_audit_log', ['ip_address'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_log_id'), 'torrent_audit_log', ['log_id'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_operation_time'), 'torrent_audit_log', ['operation_time'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_operation_type'), 'torrent_audit_log', ['operation_type'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_operator'), 'torrent_audit_log', ['operator'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_request_id'), 'torrent_audit_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_session_id'), 'torrent_audit_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_torrent_info_id'), 'torrent_audit_log', ['torrent_info_id'], unique=False)
    op.create_index(op.f('ix_torrent_audit_log_torrent_name'), 'torrent_audit_log', ['torrent_name'], unique=False)
    op.create_table('torrent_deletion_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务批次ID'),
    sa.Column('downloader_id', sa.Integer(), nullable=False, comment='下载器ID'),
    sa.Column('downloader_type', sa.Integer(), nullable=False, comment='下载器类型：0=qBittorrent, 1=Transmission'),
    sa.Column('torrent_hash', sa.String(length=64), nullable=False, comment='种子Hash'),
    sa.Column('torrent_name', sa.String(length=255), nullable=True, comment='种子名称'),
    sa.Column('torrent_size', sa.BigInteger(), nullable=True, comment='种子大小（字节）'),
    sa.Column('delete_files', sa.Boolean(), nullable=False, comment='是否删除文件'),
    sa.Column('safety_check_level', sa.String(length=20), nullable=True, comment='安全检查级别：basic/enhanced/strict'),
    sa.Column('validation_result', sa.Text(), nullable=True, comment='验证结果JSON（含seed_status、trackers等）'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作者ID：0=系统定时任务, -1=回收站清理, >0=真实用户ID'),
    sa.Column('operator_name', sa.String(length=100), nullable=True, comment='操作者用户名'),
    sa.Column('operator_ip', sa.String(length=50), nullable=True, comment='操作者IP地址'),
    sa.Column('operator_user_agent', sa.String(length=255), nullable=True, comment='操作者浏览器/客户端信息'),
    sa.Column('caller_source', sa.String(length=100), nullable=False, comment='调用来源：API/SYSTEM_SCHEDULER/RECYCLE_BIN_CLEANER'),
    sa.Column('caller_function', sa.String(length=255), nullable=True, comment='具体调用的函数'),
    sa.Column('caller_module', sa.String(length=255), nullable=True, comment='调用模块'),
    sa.Column('deletion_status', sa.String(length=20), nullable=False, comment='删除状态：success/failed/partial'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='实际删除完成时间（仅成功时设置）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torrent_deletion_audit_log_downloader_id'), 'torrent_deletion_audit_log', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_torrent_deletion_audit_log_operator_id'), 'torrent_deletion_audit_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_torrent_deletion_audit_log_task_id'), 'torrent_deletion_audit_log', ['task_id'], unique=False)
    op.create_index(op.f('ix_torrent_deletion_audit_log_torrent_hash'), 'torrent_deletion_audit_log', ['torrent_hash'], unique=False)
    op.create_table('torrent_info',
    sa.Column('info_id', sa.String(), nullable=False, comment='主键'),
    sa.Column('downloader_id', sa.String(), nullable=False, comment='所属下载器主键'),
    sa.Column('downloader_name', sa.String(), nullable=False, comment='所属下载器名称'),
    sa.Column('torrent_id', sa.String(), nullable=True, comment='下载器中的主键'),
    sa.Column('hash', sa.String(), nullable=True, comment='种子哈希值'),
    sa.Column('name', sa.String(), nullable=True, comment='种子名称'),
    sa.Column('save_path', sa.String(), nullable=True, comment='种子文件保存路径'),
    sa.Column('size', sa.Float(), nullable=True, comment='种子大小'),
    sa.Column('status', sa.String(), nullable=True, comment='状态'),
    sa.Column('progress', sa.Float(), nullable=True, comment='下载进度(0-100)'),
    sa.Column('torrent_file', sa.String(), nullable=True, comment='种子文件'),
    sa.Column('added_date', sa.DATETIME(), nullable=True, comment='添加时间'),
    sa.Column('completed_date', sa.DATETIME(), nullable=True, comment='完成时间'),
    sa.Column('ratio', sa.String(), nullable=True, comment='比率'),
    sa.Column('ratio_limit', sa.String(), nullable=True, comment='比率限制'),
    sa.Column('tags', sa.String(), nullable=True, comment='标签'),
    sa.Column('category', sa.String(), nullable=True, comment='分类'),
    sa.Column('super_seeding', sa.String(), nullable=True, comment='超级做种模式'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否停用'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', sa.String(), nullable=True, comment='创建人'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('update_by', sa.String(), nullable=True, comment='更新人'),
    sa.Column('dr', sa.Integer(), nullable=True, comment='删除状态，0是未删除，1是逻辑删除'),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True, comment='删除时间（等级3回收站）'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='原始文件名（等级3还原用）'),
    sa.Column('backup_file_path', sa.String(length=512), nullable=True, comment='种子文件备份路径（用于回收站还原）'),
    sa.Column('original_file_list', sa.Text(), nullable=True, comment='原始文件列表（JSON格式，存储相对路径，用于回收站清理）'),
    sa.Column('has_tracker_error', sa.Boolean(), nullable=False, comment='种子是否处于tracker错误状态（所有tracker都失败）'),
    sa.PrimaryKeyConstraint('info_id', 'downloader_id', 'downloader_name')
    )
    op.create_index('idx_torrent_hash_unique', 'torrent_info', ['hash', 'downloader_id'], unique=True, sqlite_where=sa.text('dr = 0'))
    op.create_index(op.f('ix_torrent_info_category'), 'torrent_info', ['category'], unique=False)
    op.create_index(op.f('ix_torrent_info_downloader_id'), 'torrent_info', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_torrent_info_downloader_name'), 'torrent_info', ['downloader_name'], unique=False)
    op.create_index(op.f('ix_torrent_info_hash'), 'torrent_info', ['hash'], unique=False)
    op.create_index(op.f('ix_torrent_info_info_id'), 'torrent_info', ['info_id'], unique=False)
    op.create_index(op.f('ix_torrent_info_name'), 'torrent_info', ['name'], unique=False)
    op.create_index(op.f('ix_torrent_info_ratio'), 'torrent_info', ['ratio'], unique=False)
    op.create_index(op.f('ix_torrent_info_ratio_limit'), 'torrent_info', ['ratio_limit'], unique=False)
    op.create_index(op.f('ix_torrent_info_save_path'), 'torrent_info', ['save_path'], unique=False)
    op.create_index(op.f('ix_torrent_info_status'), 'torrent_info', ['status'], unique=False)
    op.create_index(op.f('ix_torrent_info_super_seeding'), 'torrent_info', ['super_seeding'], unique=False)
    op.create_index(op.f('ix_torrent_info_tags'), 'torrent_info', ['tags'], unique=False)
    op.create_index(op.f('ix_torrent_info_torrent_file'), 'torrent_info', ['torrent_file'], unique=False)
    op.create_index(op.f('ix_torrent_info_torrent_id'), 'torrent_info', ['torrent_id'], unique=False)
    op.create_table('torrent_tags',
    sa.Column('tag_id', sa.String(length=36), nullable=False, comment='标签唯一标识符'),
    sa.Column('downloader_id', sa.String(length=36), nullable=False, comment='所属下载器ID'),
    sa.Column('tag_name', sa.String(length=255), nullable=False, comment='标签名称'),
    sa.Column('tag_type', sa.String(length=50), nullable=False, comment='标签类型：category/tag'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='标签颜色（HEX格式）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('dr', sa.Integer(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_torrent_tags_downloader_id'), 'torrent_tags', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_torrent_tags_tag_id'), 'torrent_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_torrent_tags_tag_type'), 'torrent_tags', ['tag_type'], unique=False)
    op.create_table('tracker_info',
    sa.Column('tracker_id', sa.String(), nullable=False, comment='主键'),
    sa.Column('torrent_info_id', sa.String(), nullable=True, comment='关联种子主键'),
    sa.Column('tracker_name', sa.String(), nullable=True, comment='tracker名称'),
    sa.Column('tracker_url', sa.String(), nullable=True, comment='tracker地址'),
    sa.Column('last_announce_succeeded', sa.Integer(), nullable=True, comment='请求结果'),
    sa.Column('last_announce_msg', sa.String(), nullable=True, comment='tracker最后一次请求信息'),
    sa.Column('last_scrape_succeeded', sa.Integer(), nullable=True, comment='汇报结果'),
    sa.Column('last_scrape_msg', sa.String(), nullable=True, comment='tracker最后一次汇报信息'),
    sa.Column('tracker_host', sa.String(length=256), nullable=True, comment='tracker主机地址'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='tracker状态: normal/error/unknown'),
    sa.Column('msg', sa.String(length=512), nullable=True, comment='tracker状态消息'),
    sa.Column('seeder_count', sa.Integer(), nullable=True, comment='做种者数量'),
    sa.Column('leecher_count', sa.Integer(), nullable=True, comment='下载者数量'),
    sa.Column('download_count', sa.Integer(), nullable=True, comment='下载完成次数'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', sa.String(), nullable=True, comment='创建人'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('update_by', sa.String(), nullable=True, comment='更新人'),
    sa.Column('dr', sa.Integer(), nullable=True, comment='删除状态，0是未删除，1是逻辑删除'),
    sa.Column('version', sa.Integer(), nullable=True, comment='乐观锁版本号'),
    sa.PrimaryKeyConstraint('tracker_id')
    )
    op.create_index('idx_tracker_unique_url', 'tracker_info', ['torrent_info_id', 'tracker_url'], unique=True, sqlite_where=sa.text('dr = 0'))
    op.create_index(op.f('ix_tracker_info_last_announce_msg'), 'tracker_info', ['last_announce_msg'], unique=False)
    op.create_index(op.f('ix_tracker_info_last_scrape_msg'), 'tracker_info', ['last_scrape_msg'], unique=False)
    op.create_index(op.f('ix_tracker_info_torrent_info_id'), 'tracker_info', ['torrent_info_id'], unique=False)
    op.create_index(op.f('ix_tracker_info_tracker_id'), 'tracker_info', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_tracker_info_tracker_name'), 'tracker_info', ['tracker_name'], unique=False)
    op.create_index(op.f('ix_tracker_info_tracker_url'), 'tracker_info', ['tracker_url'], unique=False)
    op.create_table('tracker_keyword_config',
    sa.Column('keyword_id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('keyword_type', sa.String(length=20), nullable=False, comment='关键词类型: success/failure'),
    sa.Column('keyword', sa.String(length=200), nullable=False, comment='关键词内容'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言代码(zh_CN/en_US等)，NULL表示通用'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级1-1000，数值越大优先级越高'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类标识'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='关键词说明'),
    sa.Column('create_time', sa.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=False, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=False, comment='更新人'),
    sa.Column('dr', sa.Integer(), nullable=False, comment='删除状态，0是未删除，1是逻辑删除'),
    sa.PrimaryKeyConstraint('keyword_id'),
    comment='Tracker关键词配置表'
    )
    op.create_index('idx_tracker_keyword_language', 'tracker_keyword_config', ['language'], unique=False)
    op.create_index('idx_tracker_keyword_priority', 'tracker_keyword_config', ['priority'], unique=False)
    op.create_index('idx_tracker_keyword_type_enabled', 'tracker_keyword_config', ['keyword_type', 'enabled'], unique=False)
    op.create_index('idx_tracker_keyword_unique', 'tracker_keyword_config', ['keyword'], unique=True)
    op.create_index(op.f('ix_tracker_keyword_config_keyword_id'), 'tracker_keyword_config', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_tracker_keyword_config_keyword_type'), 'tracker_keyword_config', ['keyword_type'], unique=False)
    op.create_index(op.f('ix_tracker_keyword_config_language'), 'tracker_keyword_config', ['language'], unique=False)
    op.create_table('tracker_message_log',
    sa.Column('log_id', sa.String(length=36), nullable=False, comment='主键'),
    sa.Column('tracker_host', sa.String(length=500), nullable=False, comment='tracker主机地址（用于去重）'),
    sa.Column('msg', sa.String(length=2048), nullable=False, comment='tracker返回的消息（用于去重）'),
    sa.Column('first_seen', sa.DATETIME(), nullable=False, comment='首次出现时间'),
    sa.Column('last_seen', sa.DATETIME(), nullable=False, comment='最后出现时间'),
    sa.Column('occurrence_count', sa.Integer(), nullable=False, comment='出现次数'),
    sa.Column('sample_torrents', sa.Text(), nullable=True, comment='示例种子列表(JSON)'),
    sa.Column('sample_urls', sa.Text(), nullable=True, comment='示例tracker URL列表(JSON)'),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='是否已处理（已添加到信息池）'),
    sa.Column('keyword_type', sa.String(length=20), nullable=True, comment='添加到哪个池: success/failure'),
    sa.Column('create_time', sa.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=False, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=False, comment='更新人'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='Tracker消息历史记录表'
    )
    op.create_index('idx_tracker_msg_first_seen', 'tracker_message_log', ['first_seen'], unique=False)
    op.create_index('idx_tracker_msg_is_processed', 'tracker_message_log', ['is_processed'], unique=False)
    op.create_index('idx_tracker_msg_unique', 'tracker_message_log', ['tracker_host', 'msg'], unique=True)
    op.create_index(op.f('ix_tracker_message_log_log_id'), 'tracker_message_log', ['log_id'], unique=False)
    op.create_index(op.f('ix_tracker_message_log_tracker_host'), 'tracker_message_log', ['tracker_host'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('two_factor_flag', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('downloader_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('downloader_id', sa.String(), nullable=False, comment='下载器ID，关联bt_downloaders表'),
    sa.Column('dl_speed_limit', sa.Integer(), nullable=False, comment='全局下载速度限制，数值含义取决于 dl_speed_unit，0表示不限速'),
    sa.Column('ul_speed_limit', sa.Integer(), nullable=False, comment='全局上传速度限制，数值含义取决于 ul_speed_unit，0表示不限速'),
    sa.Column('dl_speed_unit', sa.Enum('KB_PER_SEC', 'MB_PER_SEC', name='speedunitenum'), nullable=False, comment='下载速度单位：0=KB/s, 1=MB/s'),
    sa.Column('ul_speed_unit', sa.Enum('KB_PER_SEC', 'MB_PER_SEC', name='speedunitenum'), nullable=False, comment='上传速度单位：0=KB/s, 1=MB/s'),
    sa.Column('enable_schedule', sa.Boolean(), nullable=False, comment='是否启用分时段限速'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='下载器用户名（可选，用于覆盖默认配置）'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='下载器密码（SM4加密，可选，用于覆盖默认配置）'),
    sa.Column('advanced_settings', sa.Text(), nullable=True, comment='高级配置（JSON格式），存储下载器特有选项'),
    sa.Column('override_local', sa.Boolean(), nullable=False, comment='是否覆盖下载器本地配置'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['downloader_id'], ['bt_downloaders.downloader_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloader_settings_downloader_id'), 'downloader_settings', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_downloader_settings_id'), 'downloader_settings', ['id'], unique=False)
    op.create_table('setting_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称，如"qBittorrent标准模板"'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='模板描述'),
    sa.Column('downloader_type', sa.Integer(), nullable=False, comment='下载器类型：0=qBittorrent, 1=Transmission'),
    sa.Column('template_config', sa.Text(), nullable=False, comment='模板配置（JSON格式），包含速度、认证、高级设置等'),
    sa.Column('is_system_default', sa.Boolean(), nullable=False, comment='是否为系统默认模板'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者用户ID（系统默认模板为NULL）'),
    sa.Column('path_mapping', sa.Text(), nullable=True, comment='路径映射配置（JSON格式）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_setting_templates_name')
    )
    op.create_index(op.f('ix_setting_templates_created_at'), 'setting_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_setting_templates_downloader_type'), 'setting_templates', ['downloader_type'], unique=False)
    op.create_index(op.f('ix_setting_templates_id'), 'setting_templates', ['id'], unique=False)
    op.create_index(op.f('ix_setting_templates_is_system_default'), 'setting_templates', ['is_system_default'], unique=False)
    op.create_index(op.f('ix_setting_templates_name'), 'setting_templates', ['name'], unique=True)
    op.create_index(op.f('ix_setting_templates_updated_at'), 'setting_templates', ['updated_at'], unique=False)
    op.create_table('task_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='关联的定时任务ID'),
    sa.Column('task_name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('task_type', sa.Integer(), nullable=True, comment='任务类型'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='持续时间(秒)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='执行结果'),
    sa.Column('log_detail', sa.String(length=2000), nullable=True, comment='执行日志'),
    sa.Column('dr', sa.Integer(), nullable=False, comment='逻辑删除标识'),
    sa.ForeignKeyConstraint(['task_id'], ['cron_task.task_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('torrent_file_backup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('info_hash', sa.String(length=40), nullable=False, comment='种子的 info_hash（40位十六进制）'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='种子文件存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小（字节）'),
    sa.Column('task_name', sa.String(length=500), nullable=True, comment='关联的任务名称'),
    sa.Column('uploader_id', sa.Integer(), nullable=True, comment='上传用户ID'),
    sa.Column('downloader_id', sa.Integer(), nullable=True, comment='关联的下载器ID'),
    sa.Column('upload_time', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.Column('last_used_time', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('use_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['downloader_id'], ['bt_downloaders.downloader_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torrent_file_backup_downloader_id'), 'torrent_file_backup', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_torrent_file_backup_info_hash'), 'torrent_file_backup', ['info_hash'], unique=True)
    op.create_index(op.f('ix_torrent_file_backup_is_deleted'), 'torrent_file_backup', ['is_deleted'], unique=False)
    op.create_table('torrent_tag_relations',
    sa.Column('relation_id', sa.String(length=36), nullable=False, comment='关联记录唯一标识符'),
    sa.Column('downloader_id', sa.String(length=36), nullable=False, comment='下载器ID'),
    sa.Column('torrent_hash', sa.String(length=64), nullable=False, comment='种子hash值'),
    sa.Column('tag_id', sa.String(length=36), nullable=False, comment='标签ID'),
    sa.Column('assigned_at', sa.DateTime(), nullable=False, comment='分配时间'),
    sa.Column('dr', sa.Integer(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['tag_id'], ['torrent_tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('torrent_hash', 'tag_id', name='uk_torrent_tag')
    )
    op.create_index(op.f('ix_torrent_tag_relations_downloader_id'), 'torrent_tag_relations', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_torrent_tag_relations_relation_id'), 'torrent_tag_relations', ['relation_id'], unique=False)
    op.create_index(op.f('ix_torrent_tag_relations_tag_id'), 'torrent_tag_relations', ['tag_id'], unique=False)
    op.create_index(op.f('ix_torrent_tag_relations_torrent_hash'), 'torrent_tag_relations', ['torrent_hash'], unique=False)
    op.create_table('speed_schedule_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('downloader_setting_id', sa.Integer(), nullable=False, comment='下载器配置ID，关联downloader_settings表'),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment='开始时间，格式"HH:MM"，如"08:00"'),
    sa.Column('end_time', sa.String(length=5), nullable=False, comment='结束时间，格式"HH:MM"，如"18:00"'),
    sa.Column('dl_speed_limit', sa.Integer(), nullable=False, comment='下载速度限制（KB/s），0表示不限速'),
    sa.Column('ul_speed_limit', sa.Integer(), nullable=False, comment='上传速度限制（KB/s），0表示不限速'),
    sa.Column('dl_speed_unit', sa.Integer(), server_default='0', nullable=False, comment='下载速度单位：0=KB/s, 1=MB/s'),
    sa.Column('ul_speed_unit', sa.Integer(), server_default='0', nullable=False, comment='上传速度单位：0=KB/s, 1=MB/s'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='规则排序（同一下载器内），数字越小优先级越高'),
    sa.Column('days_of_week', sa.String(length=7), nullable=False, comment='生效星期几，0=周日，1=周一，...，6=周六'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint("days_of_week >= '0' AND days_of_week <= '6543210'", name='ck_days_of_week_format'),
    sa.CheckConstraint('start_time < end_time', name='ck_start_time_before_end_time'),
    sa.ForeignKeyConstraint(['downloader_setting_id'], ['downloader_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speed_schedule_rules_downloader_setting_id'), 'speed_schedule_rules', ['downloader_setting_id'], unique=False)
    op.create_index(op.f('ix_speed_schedule_rules_id'), 'speed_schedule_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speed_schedule_rules_id'), table_name='speed_schedule_rules')
    op.drop_index(op.f('ix_speed_schedule_rules_downloader_setting_id'), table_name='speed_schedule_rules')
    op.drop_table('speed_schedule_rules')
    op.drop_index(op.f('ix_torrent_tag_relations_torrent_hash'), table_name='torrent_tag_relations')
    op.drop_index(op.f('ix_torrent_tag_relations_tag_id'), table_name='torrent_tag_relations')
    op.drop_index(op.f('ix_torrent_tag_relations_relation_id'), table_name='torrent_tag_relations')
    op.drop_index(op.f('ix_torrent_tag_relations_downloader_id'), table_name='torrent_tag_relations')
    op.drop_table('torrent_tag_relations')
    op.drop_index(op.f('ix_torrent_file_backup_is_deleted'), table_name='torrent_file_backup')
    op.drop_index(op.f('ix_torrent_file_backup_info_hash'), table_name='torrent_file_backup')
    op.drop_index(op.f('ix_torrent_file_backup_downloader_id'), table_name='torrent_file_backup')
    op.drop_table('torrent_file_backup')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_setting_templates_updated_at'), table_name='setting_templates')
    op.drop_index(op.f('ix_setting_templates_name'), table_name='setting_templates')
    op.drop_index(op.f('ix_setting_templates_is_system_default'), table_name='setting_templates')
    op.drop_index(op.f('ix_setting_templates_id'), table_name='setting_templates')
    op.drop_index(op.f('ix_setting_templates_downloader_type'), table_name='setting_templates')
    op.drop_index(op.f('ix_setting_templates_created_at'), table_name='setting_templates')
    op.drop_table('setting_templates')
    op.drop_index(op.f('ix_downloader_settings_id'), table_name='downloader_settings')
    op.drop_index(op.f('ix_downloader_settings_downloader_id'), table_name='downloader_settings')
    op.drop_table('downloader_settings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracker_message_log_tracker_host'), table_name='tracker_message_log')
    op.drop_index(op.f('ix_tracker_message_log_log_id'), table_name='tracker_message_log')
    op.drop_index('idx_tracker_msg_unique', table_name='tracker_message_log')
    op.drop_index('idx_tracker_msg_is_processed', table_name='tracker_message_log')
    op.drop_index('idx_tracker_msg_first_seen', table_name='tracker_message_log')
    op.drop_table('tracker_message_log')
    op.drop_index(op.f('ix_tracker_keyword_config_language'), table_name='tracker_keyword_config')
    op.drop_index(op.f('ix_tracker_keyword_config_keyword_type'), table_name='tracker_keyword_config')
    op.drop_index(op.f('ix_tracker_keyword_config_keyword_id'), table_name='tracker_keyword_config')
    op.drop_index('idx_tracker_keyword_unique', table_name='tracker_keyword_config')
    op.drop_index('idx_tracker_keyword_type_enabled', table_name='tracker_keyword_config')
    op.drop_index('idx_tracker_keyword_priority', table_name='tracker_keyword_config')
    op.drop_index('idx_tracker_keyword_language', table_name='tracker_keyword_config')
    op.drop_table('tracker_keyword_config')
    op.drop_index(op.f('ix_tracker_info_tracker_url'), table_name='tracker_info')
    op.drop_index(op.f('ix_tracker_info_tracker_name'), table_name='tracker_info')
    op.drop_index(op.f('ix_tracker_info_tracker_id'), table_name='tracker_info')
    op.drop_index(op.f('ix_tracker_info_torrent_info_id'), table_name='tracker_info')
    op.drop_index(op.f('ix_tracker_info_last_scrape_msg'), table_name='tracker_info')
    op.drop_index(op.f('ix_tracker_info_last_announce_msg'), table_name='tracker_info')
    op.drop_index('idx_tracker_unique_url', table_name='tracker_info', sqlite_where=sa.text('dr = 0'))
    op.drop_table('tracker_info')
    op.drop_index(op.f('ix_torrent_tags_tag_type'), table_name='torrent_tags')
    op.drop_index(op.f('ix_torrent_tags_tag_id'), table_name='torrent_tags')
    op.drop_index(op.f('ix_torrent_tags_downloader_id'), table_name='torrent_tags')
    op.drop_table('torrent_tags')
    op.drop_index(op.f('ix_torrent_info_torrent_id'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_torrent_file'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_tags'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_super_seeding'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_status'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_save_path'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_ratio_limit'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_ratio'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_name'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_info_id'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_hash'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_downloader_name'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_downloader_id'), table_name='torrent_info')
    op.drop_index(op.f('ix_torrent_info_category'), table_name='torrent_info')
    op.drop_index('idx_torrent_hash_unique', table_name='torrent_info', sqlite_where=sa.text('dr = 0'))
    op.drop_table('torrent_info')
    op.drop_index(op.f('ix_torrent_deletion_audit_log_torrent_hash'), table_name='torrent_deletion_audit_log')
    op.drop_index(op.f('ix_torrent_deletion_audit_log_task_id'), table_name='torrent_deletion_audit_log')
    op.drop_index(op.f('ix_torrent_deletion_audit_log_operator_id'), table_name='torrent_deletion_audit_log')
    op.drop_index(op.f('ix_torrent_deletion_audit_log_downloader_id'), table_name='torrent_deletion_audit_log')
    op.drop_table('torrent_deletion_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_torrent_name'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_torrent_info_id'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_session_id'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_request_id'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_operator'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_operation_type'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_operation_time'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_log_id'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_ip_address'), table_name='torrent_audit_log')
    op.drop_index(op.f('ix_torrent_audit_log_downloader_id'), table_name='torrent_audit_log')
    op.drop_table('torrent_audit_log')
    op.drop_index(op.f('ix_seed_transfer_audit_log_user_id'), table_name='seed_transfer_audit_log')
    op.drop_index(op.f('ix_seed_transfer_audit_log_transfer_status'), table_name='seed_transfer_audit_log')
    op.drop_index(op.f('ix_seed_transfer_audit_log_operation_time'), table_name='seed_transfer_audit_log')
    op.drop_index(op.f('ix_seed_transfer_audit_log_info_hash'), table_name='seed_transfer_audit_log')
    op.drop_table('seed_transfer_audit_log')
    op.drop_index(op.f('ix_login_logs_id'), table_name='login_logs')
    op.drop_table('login_logs')
    op.drop_index(op.f('ix_downloader_path_maintenance_path_type'), table_name='downloader_path_maintenance')
    op.drop_index(op.f('ix_downloader_path_maintenance_downloader_id'), table_name='downloader_path_maintenance')
    op.drop_table('downloader_path_maintenance')
    op.drop_index(op.f('ix_downloader_capabilities_id'), table_name='downloader_capabilities')
    op.drop_index(op.f('ix_downloader_capabilities_downloader_setting_id'), table_name='downloader_capabilities')
    op.drop_index(op.f('ix_downloader_capabilities_downloader_id'), table_name='downloader_capabilities')
    op.drop_table('downloader_capabilities')
    op.drop_table('cron_task')
    op.drop_table('configs')
    op.drop_index(op.f('ix_bt_downloaders_username'), table_name='bt_downloaders')
    op.drop_index(op.f('ix_bt_downloaders_port'), table_name='bt_downloaders')
    op.drop_index(op.f('ix_bt_downloaders_nickname'), table_name='bt_downloaders')
    op.drop_index(op.f('ix_bt_downloaders_host'), table_name='bt_downloaders')
    op.drop_index(op.f('ix_bt_downloaders_downloader_id'), table_name='bt_downloaders')
    op.drop_table('bt_downloaders')
    # ### end Alembic commands ###
